name: ci

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install bun
      uses: oven-sh/setup-bun@v1
    
    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Validate current commit (last commit) with commitlint
      if: github.event_name == 'push'
      run: bunx commitlint --last --verbose

    - name: Validate PR commits with commitlint
      if: github.event_name == 'pull_request'
      run: bunx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

    - name: Lint and check formatting
      run: bun run check
    
    - name: Build app
      run: bun run build